---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_postfix"
      tags:
        - "labocbz.install_postfix"
      vars:
        install_postfix__email_sender: "{{ inv_install_postfix__email_sender }}"
        install_postfix__email_sender_address: "{{ inv_install_postfix__email_sender_address }}"
        install_postfix__email_sender_api_key: "{{ inv_install_postfix__email_sender_api_key }}"
        install_postfix__aliases_addresses: "{{ inv_install_postfix__aliases_addresses }}"
        install_postfix__esmtp_banner: "{{ inv_install_postfix__esmtp_banner }}"
      ansible.builtin.include_role:
        name: "labocbz.install_postfix"
