---
- name: "Start and enable Postfix"
  register: postfix_service_status
  changed_when: postfix_service_status.state != "started"
  ansible.builtin.service:
    name: "postfix"
    state: "started"
    enabled: yes

- name: "Restart Postfix"
  register: postfix_service_status
  changed_when: postfix_service_status.state != "restarted"
  ansible.builtin.service:
    name: "postfix"
    state: "restarted"
    daemon_reload: true
